name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  first:
    name: Homework Grade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Annotate
      #   run: |
      #     echo "::group::My title"
      #     echo "Inside group"
      #     echo "::endgroup::"
      #     echo "::error file=app.js::school.sh must use 'cat' statement"
      #     echo "::notice file=school.sh::school.sh must use 'cat' statement"
      #     echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Mark It
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      # - name: Bash running
      #   run: |
      #     ./test_suite/log.sh
      - name: Check School
        id: school
        run: |
          ./test_suite/check_school.sh
      - name: Check Five
        id: five
        run: |
          ./test_suite/check_five.sh
      - name: Get Points
        run: |
          echo "::notice::School points is ${{ steps.school.outputs.points_school }}. Five points is ${{ steps.five.outputs.points_five }}"

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     if: github.actor != 'github-classroom[bot]'
#     steps:
#       - uses: actions/checkout@v4
#       - uses: education/autograding@v1
# 			- run: |
#             echo "::group::My title"
#             echo "Inside group"
#             echo "::endgroup::"
# 			- run: |
# 						echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
# 						echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
# 						echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
# 						echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
# 						echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
